// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHppUvKzI04BuGVWa75hnvm5QWLPhqT0w',
    appId: '1:1082544990701:web:bfbb79a16a6cf44351dfe4',
    messagingSenderId: '1082544990701',
    projectId: 'testing-cli-9be52',
    authDomain: 'testing-cli-9be52.firebaseapp.com',
    storageBucket: 'testing-cli-9be52.firebasestorage.app',
    measurementId: 'G-PM0LYGG1JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH9jKNHoDzIqNRJHpyWJcYOVDXcqy42F8',
    appId: '1:1082544990701:android:dfb70926b907576851dfe4',
    messagingSenderId: '1082544990701',
    projectId: 'testing-cli-9be52',
    storageBucket: 'testing-cli-9be52.firebasestorage.app',
  );
}
